import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
    const [form, setForm] = useState({
        phone: "",
        message: "",
        success: "",
        error: "",
    });

    const { phone, message, error, success } = form;

    //handle change
    const handleChange = (evt) => {
        const value = evt.target.value;
        setForm({
            ...form,
            [evt.target.name]: value,
        });
    };
    const handleSubmit = async (e) => {
        e.preventDefault();
        //check errors
        if (phone.length < 7 && message.length < 1)
            return setForm({
                ...form,
                error: "Please enter a valid phone number and write a message",
            });

        //send a post req to send SMS
        const sms = await fetch(
            "http://vfzwlkqneu.us08.qoddiapp.com/send-sms",
            {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({ phone, message }),
            }
        );

        //check if sms was sent
        if (sms.ok) {
            setForm({
                phone: "",
                message: "",
                error: "",
                success: "Message send successfully",
            });
        } else {
            setForm({
                ...form,
                error: "Message failed to send",
            });
        }
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Send A SMS To A Phone Number From Web!
                </h1>

                <p className={styles.description}>With Twilio From Node.js</p>

                {/* create a form to send sms  */}
                <form className={styles.form} onSubmit={handleSubmit}>
                    <p>{error}</p>
                    <p>{success}</p>
                    <label className={styles.label}>
                        Phone Number:
                        <br />
                        <input
                            className={styles.input}
                            type="text"
                            name="phone"
                            value={form.phone}
                            onChange={handleChange}
                        />
                    </label>
                    <br />
                    <label className={styles.label}>
                        Message: <br />
                        <textarea
                            className={styles.textarea}
                            name="message"
                            value={form.message}
                            onChange={handleChange}
                        />
                    </label>
                    <br />
                    <button className={styles.button} type="submit">
                        Send SMS ---
                    </button>
                </form>
            </main>

            <footer className={styles.footer}>Hello World!</footer>
        </div>
    );
}
